config/routes.rb
Rails.application.routes.draw do
  root 'index#index'

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  { class_name: 'User' }.merge(ActiveAdmin::Devise.config)
  ActiveAdmin.routes(self)

  get 'users/profile', as: 'user_root'

  resources :movies do
    resources :likes, only: [:create, :destroy]
    resources :wishes, only: [:create, :destroy]
    resources :comments
  end

  resources :serials do 
    resources :likes, only: [:create, :destroy]
    resources :wishes, only: [:create, :destroy]
    resources :comments
  end

  resources :seasons do 
    resources :likes, only: [:create, :destroy]
    resources :wishes, only: [:create, :destroy]
    resources :comments
  end

  resources :series do 
    resources :comments
  end

  resources :directors, :actors
  get 'search', to: 'search#search'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/wish.rb
class Wish < ApplicationRecord
  belongs_to :wishable, polymorphic: true
  belongs_to :user
end

app/controllers/wishes_controller.rb
class WishesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_wishable

  def create
    current_user.add_wish_to(@wishable)

    respond_to do |format|
      format.html { redirect_to :back }
      format.js { render layout: false }
    end
  end

  def destroy
    current_user.remove_wish_from(@wishable)

    respond_to do |format|
      format.html { redirect_to :back }
      format.js { render layout: false }
    end
  end

  private

  def set_wishable
    @wishable = Movie.find(params[:movie_id]) unless params[:movie_id].nil?
    @wishable = Serial.find(params[:serial_id]) unless params[:serial_id].nil?
    @wishable
  end
end

app/helpers/wish_helper.rb
module WishHelper
end

app/views/wishes/_unwish.html.haml
-if wishable.class.to_s == "Movie"
  = link_to movie_wish_path(wishable, 1), method: "delete", remote: true do
    %h3.bi.bi-star-fill
  %h3.count= wishable.wishes.count
-if wishable.class.to_s == "Serial"
  = link_to serial_wish_path(wishable, 1), method: "delete", remote: true do
    %h3.bi.bi-star-fill
  %h3.count= wishable.wishes.count

app/views/wishes/_wish.html.haml
-if wishable.class.to_s == "Movie"
  = link_to movie_wishes_path(movie_id: wishable.id), remote: true, method: :post do
    %h3.bi.bi-star
  %h3.count= wishable.likes.count
-if wishable.class.to_s == "Serial"
  = link_to serial_wishes_path(serial_id: wishable.id), remote: true, method: :post do
    %h3.bi.bi-star
  %h3.count= wishable.likes.count

app/views/wishes/create.js.erb
document.activeElement.parentElement.innerHTML = ("<%= j(render(partial: 'wishes/unwish', locals: { wishable: @wishable })) %>")

app/views/wishes/destroy.js.erb
document.activeElement.parentElement.innerHTML = ("<%= j(render(partial: 'wishes/wish', locals: { wishable: @wishable })) %>")