config/routes.rb
Rails.application.routes.draw do
  root 'index#index'

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  { class_name: 'User' }.merge(ActiveAdmin::Devise.config)
  ActiveAdmin.routes(self)

  get 'users/profile', as: 'user_root'

  resources :movies do
    resources :likes, only: [:create, :destroy]
    resources :wishes, only: [:create, :destroy]
    resources :comments
  end

  resources :serials do 
    resources :likes, only: [:create, :destroy]
    resources :wishes, only: [:create, :destroy]
    resources :comments
  end

  resources :seasons do 
    resources :likes, only: [:create, :destroy]
    resources :wishes, only: [:create, :destroy]
    resources :comments
  end

  resources :series do 
    resources :comments
  end

  resources :directors, :actors
  get 'search', to: 'search#search'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/season.rb
class Season < ApplicationRecord
  belongs_to :serial
  has_many :series
  has_many :seasons_actor
  has_many :actors, through: :seasons_actor

  has_many :comments, as: :commentable

  has_many :likes, as: :likeable
  has_many :liked_users, through: :like
  has_many :wishes, as: :wishable
  has_many :wished_users, through: :wish
  has_many :comments, as: :commentable

  paginates_per 4
end

app/controllers/seasons_controller.rb
class SeasonsController < ApplicationController
  before_action :set_season, only: %i[show]
  before_action :set_serial, only: [:show]

  def index
    @seasons = Season.all
  end

  def show
    get_series
    get_actors
    set_serials
    get_serial_seasons
    get_comments
  end

  private

  def set_season
    @season ||= Season.find(params[:id])
  end

  def set_serial
    @serial = Serial.find(@season.serial_id) 
  end

  def set_serials
    @serials ||= Serial.all.where(category: @serial.category).where.not(id: @serial.id)
  end

  def get_serial_seasons
    @seasons = Season.all.where(serial_id: @serial.id).where.not(id: @season.id)
  end

  def get_actors
    @actors = @season.actors
  end

  def get_series
    @series ||= @season.series
  end

  def get_comments
    @comments = Kaminari.paginate_array(@season.comments).page(params[:page]).per(4)
  end
end

app/helpers/seasons_helper.rb
module SeasonsHelper
end

app/views/seasons/_season.html.haml
= link_to season_path(season.id) do
  %li
    %img{ src: "https://image.tmdb.org/t/p/w185#{season.image}", class: 'actor-img'}
    %br
    = link_to season.name, season_path(season.id), class: 'link'

app/views/seasons/show.html.haml
%br
.movie-main
  %h3.font-weight-bold{style: "padding-left: 7%"}= is_exist(@season.name)
  .container
    .row
      .col-4
        -if @season.image 
          %img.movie-img{ src: "https://image.tmdb.org/t/p/w300#{@season.image}", alt: @season.name }
        -else
          =image_tag 'download.png', class: 'movie-no-img'
      .col-8
        %h4.video-section= t('trailer')
        %iframe.video{ src: "https://www.youtube.com/embed/#{@season.video_key}" }
        %h4.section-name= t('overview')
        .text-justify= is_exist(@season.description)
    .row
      .col-12
        %h4.section-name= t('series')
        %ul.series-list
          =render @series
    .row
      .col-12
        %h4.section-name= t('actors')
        %ul.actor-list
          =render @actors
    -if @seasons.count > 0
      .row
        .col-12
          %h4.section-name= t('all_seasons')
          %ul.actor-list
            =render @seasons
    .row
      .col-12
        - if @season.comments.count > 0
          %h4.section-name= "#{t('comments')} (#{@season.comments.count})"
          %br
          %ul.be-comment-block#comments
            =render @comments
          =paginate @comments
        -if !current_user.nil?
          =render("comments/create", commentable: @season)
    .row
      %h4.section-name= t('like_it')
      .col-12
        %ul.home-movie-list
          -@serials.each do |serial|
            = link_to serial_path(serial) do
              %li.movie-title
                -if serial.image
                  %img.movie-home-img{ src: "https://image.tmdb.org/t/p/w300#{serial.image}", alt: serial.name }
                - else
                  %img.movie-no-img    
                %br
                = link_to serial.name, serial_path(serial), class: 'link'
                .small= serial.release_date.year