config/routes.rb
Rails.application.routes.draw do
  root 'index#index'

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  { class_name: 'User' }.merge(ActiveAdmin::Devise.config)
  ActiveAdmin.routes(self)

  get 'users/profile', as: 'user_root'

  resources :movies do
    resources :likes, only: [:create, :destroy]
    resources :wishes, only: [:create, :destroy]
    resources :comments
  end

  resources :serials do 
    resources :likes, only: [:create, :destroy]
    resources :wishes, only: [:create, :destroy]
    resources :comments
  end

  resources :seasons do 
    resources :likes, only: [:create, :destroy]
    resources :wishes, only: [:create, :destroy]
    resources :comments
  end

  resources :series do 
    resources :comments
  end

  resources :directors, :actors
  get 'search', to: 'search#search'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: %i[show like unlike]
  before_action :set_movies, only: [:show]

  def index
    @movies = Movie.all
  end

  def show
    get_actors
    get_comments
  end

  private

  def set_movie
    @movie ||= Movie.find(params[:id])
  end

  def set_movies
    @movies ||= Movie.all.where(category: @movie.category).where.not(id: @movie.id)
  end

  def get_actors
    @actors ||= @movie.actors
  end

  def get_comments
    @comments = Kaminari.paginate_array(@movie.comments).page(params[:page]).per(4)
  end
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/movies/_movie.html.haml
= link_to movie_path(movie), class: "profile-tab-link" do
  %li.movie-item-prodile
    %h6=movie.name
    .small= "#{t('duration')}: #{movie.duration}" 
    %br

app/views/movies/index.html.haml
.main 
  %h3.section-name= t('films')
  %ul.movie-list
    -@movies.each do |movie|
      = link_to movie_path(movie) do
        %li.movie-title
          -if movie.image
            %img.movie-home-img{ src: "https://image.tmdb.org/t/p/w300#{movie.image}", alt: movie.name }
          - else
            %img.movie-no-img    
          %br
          = link_to movie.name, movie_path(movie), class: 'link'
          .small= movie.release_date.year

app/views/movies/show.html.haml
%br
.movie-main
  %h3.font-weight-bold{style: "padding-left: 7%"}= @movie.name
  .container
    .row
      .col-4
        -if @movie.image 
          %img.movie-img{ src: "https://image.tmdb.org/t/p/w300#{@movie.image}", alt: @movie.name }
        -else
          %img.movie-no-img
      .col-8
        %h4.video-section= t('trailer')
        %iframe.video{ src: "https://www.youtube.com/embed/#{@movie.video_key}" }
    .row
      .col-4
        %br
        .control-container
          #like-container
            - if !current_user.nil? && current_user.liked?("Movie", @movie.id)
              = render("likes/unlike", likeable: @movie)
            - else
              = render("likes/like", likeable: @movie)
          #wish-container
            -if !current_user.nil? && current_user.wished?("Movie", @movie.id)
              = render("wishes/unwish", wishable: @movie)
            - else
              = render("wishes/wish", wishable: @movie)
        %br
        %ul.attributes-list
          %li
            .attribute-name= t('director')
            -if @movie.director&.full_name.nil?
              .attribute-value no info
            -else 
              = link_to "#{@movie.director&.full_name}", director_path(@movie.director), class: 'attribute-link'
          %li
            .attribute-name= t('category')
            .attribute-value= is_exist(@movie.category&.name)
          %li
            .attribute-name= t('duration')
            .attribute-value= is_exist(@movie.duration)
          %li
            .attribute-name= t('release_date')
            .attribute-value= is_exist(@movie.release_date)
      .col-8
        %h4.section-name= t('overview')
        .text-justify= is_exist(@movie.description)
        %h4.section-name= t('actors')
        %ul.actor-list
          =render @actors
    .row
      .col-12
        - if @movie.comments.count > 0
          %h4.section-name= "#{t('comments')} (#{@movie.comments.count})"
          %br
          %ul.be-comment-block#comments
            =render @comments
          =paginate @comments
        -if !current_user.nil?
          =render("comments/create", commentable: @movie)
    %h4.section-name= t('like_it')
    .row
      %ul.home-movie-list
        -@movies.each do |movie|
          = link_to movie_path(movie) do
            %li.movie-title
              -if movie.image
                %img.movie-home-img{ src: "https://image.tmdb.org/t/p/w300#{movie.image}", alt: movie.name }
              - else
                %img.movie-no-img    
              %br
              = link_to movie.name, movie_path(movie), class: 'link'
              .small= movie.release_date.year