config/routes.rb
Rails.application.routes.draw do
  root 'index#index'

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  { class_name: 'User' }.merge(ActiveAdmin::Devise.config)
  ActiveAdmin.routes(self)

  get 'users/profile', as: 'user_root'

  resources :movies do
    resources :likes, only: [:create, :destroy]
    resources :wishes, only: [:create, :destroy]
    resources :comments
  end

  resources :serials do 
    resources :likes, only: [:create, :destroy]
    resources :wishes, only: [:create, :destroy]
    resources :comments
  end

  resources :seasons do 
    resources :likes, only: [:create, :destroy]
    resources :wishes, only: [:create, :destroy]
    resources :comments
  end

  resources :series do 
    resources :comments
  end

  resources :directors, :actors
  get 'search', to: 'search#search'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/series_controller.rb
class SeriesController < ApplicationController
  before_action :set_serie, only: %i[show]
  before_action :get_season, only: [:show]

  def show
    set_serial
    get_serials
    get_other_series
    get_comments
  end

  private

  def set_serie
    @serie ||= Series.find(params[:id])
  end

  def get_other_series
    @series ||= Series.all.where(season_id: @serie.season_id).where.not(id: @serie.id)
  end

  def get_season
    @season ||= Season.find(@serie.season_id)
  end

  def set_serial
    @serial = Serial.find(@season.serial_id) 
  end

  def get_serials
    @serials ||= Serial.all.where(category: @serial.category).where.not(id: @serial.id)
  end

  def get_comments
    @comments = Kaminari.paginate_array(@serie.comments).page(params[:page]).per(4)
  end
end

app/helpers/series_helper.rb
module SeriesHelper
end

app/views/series/_series.html.haml
= link_to series_path(series.id) do
  %li
    -if series.image
      %img{ src: "https://image.tmdb.org/t/p/w185#{series.image}", class: 'series-img'}
    -else
      =image_tag 'download.png', class: 'series-img'
    %br 
    = link_to series.name, series_path(series.id), class: 'link'

app/views/series/show.html.haml
%br
.movie-main
  %h3.font-weight-bold{style: "padding-left: 7%"}= @serie.name
  .container
    .row
      .col-4
        -if @serie.image 
          %img.movie-img{ src: "https://image.tmdb.org/t/p/w300#{@serie.image}", alt: @serie.name }
        -else
          =image_tag 'download.png', class: 'series-img'
      .col-8
        %h4.section-name= t('overview')
        .text-justify= @serie.description
    .row
      .col-12
        %h4.section-name= t('all_series')
        %ul.series-list
          =render @series
    .row
      .col-12
        - if @season.comments.count > 0
          %h4.section-name= "#{t('comments')} (#{@season.comments.count})"
          %br
          %ul.be-comment-block#comments
            =render @comments
          =paginate @comments
        -if !current_user.nil?
          =render("comments/create", commentable: @season)
    .row
      %h4.section-name= t('like_it')
      .col-12
        %ul.home-movie-list
          -@serials.each do |serial|
            = link_to serial_path(serial) do
              %li.movie-title
                -if serial.image
                  %img.movie-home-img{ src: "https://image.tmdb.org/t/p/w300#{serial.image}", alt: serial.name }
                - else
                  %img.movie-no-img    
                %br
                = link_to serial.name, serial_path(serial), class: 'link'
                .small= serial.release_date.year